apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-hello-world
spec:
  replicas: 1
  template:
    metadata:
      name: python-hello-world
      labels:
        app: python-hello-world
        type: simpleservice
    spec:
      containers:
      - name: python-hello-world
        image: sangam21/sangam-repo:latest
        ports:
        - containerPort: 5000
  selector: 
    matchLabels:
      app: python-hello-world
      
      
---
apiVersion: v1
kind: Service
metadata:
  name: python-hello-world-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: python-hello-world
